name: Delete Neon Branch with GitHub Actions Demo
run-name: Delete a Neon Branch 🚀
on: [push]
jobs:
  delete-neon-branch:
    uses: neondatabase/delete-branch-action@v3
    with:
      project_id: morning-mouse-63689729
      branch: br-ancient-sun-a2fayqwq
      api_key: ${{ secrets.NEON_API_KEY }}